//============================================================================
//
//  This program is free software; you can redistribute it and/or modify it
//  under the terms of the GNU General Public License as published by the Free
//  Software Foundation; either version 2 of the License, or (at your option)
//  any later version.
//
//  This program is distributed in the hope that it will be useful, but WITHOUT
//  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
//  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
//  more details.
//
//  You should have received a copy of the GNU General Public License along
//  with this program; if not, write to the Free Software Foundation, Inc.,
//  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//
//============================================================================

module emu
(
	`include "sys/emu_ports.vh"
);

///////// Default values for ports not used in this core /////////

assign ADC_BUS  = 'Z;
assign USER_OUT = '1;
assign {UART_RTS, UART_TXD, UART_DTR} = 0;
assign {SD_SCK, SD_MOSI, SD_CS} = 'Z;
assign {SDRAM_DQ, SDRAM_A, SDRAM_BA, SDRAM_CLK, SDRAM_CKE, SDRAM_DQML, SDRAM_DQMH, SDRAM_nWE, SDRAM_nCAS, SDRAM_nRAS, SDRAM_nCS} = 'Z;
// DDRAM/FB_* are driven by screen_rotate below (Turbo's native raster is
// portrait, MAME ROT270 -- see the screen_rotate instantiation for why).
assign FB_FORCE_BLANK = 0;

assign VGA_SL = 0;
assign VGA_F1 = 0;
assign VGA_SCALER  = 0;
assign VGA_DISABLE = 0;
assign HDMI_FREEZE = 0;
assign HDMI_BLACKOUT = 0;
assign HDMI_BOB_DEINT = 0;

// Sound board 834-5122, modelled discretely in rtl/audio. AUDIO_S = 1
// because the mixer works in signed volts about the board's 6 V mid-rail.
// AUDIO_MIX = 0: the cabinet is mono, so there is nothing for the
// framework to blend.
assign AUDIO_S = 1;
assign AUDIO_L = audio_l;
assign AUDIO_R = audio_r;
assign AUDIO_MIX = 0;

assign LED_DISK = 0;
assign LED_POWER = 0;
assign BUTTONS = 0;

//////////////////////////////////////////////////////////////////

wire [1:0] ar = status[122:121];

// "Original" (ar==0) swaps to 3:4 when Turbo's rotated picture is actually
// being sent to the HDMI framebuffer (~no_rotate, same signal screen_rotate
// below uses) -- otherwise the scaler keeps stretching the now-portrait
// image into the landscape 4:3 declared for Buck Rogers, matching
// Arcade-DonkeyKong_MiSTer's identical VIDEO_ARX/ARY swap pattern for its
// own rotated cabinet. "Full Screen"/[ARC1]/[ARC2] (ar!=0) are explicit
// user overrides and are left alone either way.
assign VIDEO_ARX = (!ar) ? (no_rotate ? 12'd4 : 12'd3) : (ar - 1'd1);
assign VIDEO_ARY = (!ar) ? (no_rotate ? 12'd3 : 12'd4) : 12'd0;

`include "build_id.v"
localparam CONF_STR = {
	"SegaVCO;;",
	"-;",
	"O[122:121],Aspect ratio,Original,Full Screen,[ARC1],[ARC2];",
	// Turbo's native raster is portrait (MAME lists turbo as ROT270; Buck
	// Rogers/buckrogn are ROT0). This option only affects the HDMI
	// framebuffer-scaler path (screen_rotate below writes a rotated copy
	// to DDRAM); VGA output is always the raw, unrotated picture, matching
	// a genuinely rotated cabinet monitor wired via VGA. No effect on Buck
	// Rogers (forced off below regardless of this bit).
	// H0 hides these two Turbo-only entries when Buck Rogers is loaded
	// (status_menumask[0] driven by ~mod_turbo below) -- no point showing
	// Turbo's rotate/steering options on a game that ignores both bits.
	"H0O[6],Rotate HDMI (Turbo),Auto,Off;",
	"H0O[10],D-Pad Steering (Turbo),Velocity,Position;",
	"-;",
	// DIP switch VALUES are not declared here -- per MiSTer arcade-core
	// convention (mister-devel MkDocs_MiSTer, developer/mra) they live in
	// each game's MRA <switches>/<dip> elements, sent to the core over
	// ioctl_index==254 as up to 8 raw bytes (sw[0..7] below) -- NOT baked
	// into CONF_STR as O/P1O/P2O options driven by `status`. This also
	// fixes DIP settings not persisting: MRA-sourced DIPs are saved/
	// restored per-game by the OSD, where CONF_STR status bits are one
	// core-wide blob that doesn't survive switching games. See dsw1/dsw2/
	// turbo_dsw1/turbo_dsw2/turbo_dsw3 below.
	//
	// The literal "DIP;" entry below IS still required, though: confirmed
	// against Darius_MiSTer/Template.sv (a working reference core) that
	// this is the placeholder that tells the OSD to render the MRA-sourced
	// DIP switches page at this position in the menu -- omitting it (the
	// original mistake here) leaves the OSD with no DIP page at all, MRA
	// <switches> or not. Buck Rogers and Turbo ship different <switches>
	// blocks in their own .mra files (mra/buckrog.mra, mra/buckrogn.mra,
	// mra/turbo.mra, generated by tools/gen_mra.py), so no H1/h1
	// page-hiding is needed the way the old CONF_STR-embedded DIPs required.
	"DIP;",
	"-;",
	// T[0]/R[0] both on status bit 0, matching Darius_MiSTer/Template.sv AND
	// this user's own SuperOffRoad_MiSTer/SuperOffRoad.sv verbatim -- do not
	// change this again without hardware evidence specific to THIS core.
	//
	// MUST come before J1: J1 is a non-OSD directive (joystick button-name
	// binding, not a menu entry) and per mister-devel's CONF_STR reference,
	// non-OSD directives belong at the bottom of CONF_STR, after all real
	// menu entries. Both reference cores above follow this -- T[0]/R[0]
	// precede J1 in both -- and this core had it backwards (J1 before the
	// reset entries), which is consistent with T[0] not triggering and R[0]
	// not being recognized as the close-OSD variant.
	"T[0],Reset;",
	"R[0],Reset and close OSD;",
	// Only the buttons the game actually has -- no placeholder entries. Start/
	// Coin are the shared bit positions (joystick_0/1[7]/[8]) both games use,
	// and P2 takes its own controller's copies of the SAME bit positions, so
	// P2 start and P2 coin never land on P1's pad. Turbo's own Gear Shift/
	// Pedal are appended at the end rather than reusing Buck's Fire/Accel
	// bits, so neither game's button list disturbs the other's bit positions.
	// Names must match <buttons names="..."> in mra/*.mra.
	"J1,Fire,Accel Fast,Accel Slow,Start,Coin,Gear Shift,Pedal;",
	"v,0;", // [optional] config version 0-99.
	        // If CONF_STR options are changed in incompatible way, then change version number too,
			  // so all options will get default values on first start.
	"V,v",`BUILD_DATE
};

wire forced_scandoubler;
wire   [1:0] buttons;
wire [127:0] status;
wire  [10:0] ps2_key;

wire [31:0] joystick_0, joystick_1;
wire [15:0] joystick_l_analog_0;
wire  [8:0] spinner_0;

wire        ioctl_download;
wire        ioctl_wr;
wire [24:0] ioctl_addr;
wire [7:0]  ioctl_dout;
wire [15:0] ioctl_index;

hps_io #(.CONF_STR(CONF_STR)) hps_io
(
	.clk_sys(clk_sys),
	.HPS_BUS(HPS_BUS),
	.EXT_BUS(),
	.gamma_bus(),

	.forced_scandoubler(forced_scandoubler),

	.joystick_0(joystick_0),
	.joystick_1(joystick_1),
	.joystick_l_analog_0(joystick_l_analog_0),
	.spinner_0(spinner_0),

	.ioctl_download(ioctl_download),
	.ioctl_wr(ioctl_wr),
	.ioctl_addr(ioctl_addr),
	.ioctl_dout(ioctl_dout),
	.ioctl_index(ioctl_index),

	.buttons(buttons),
	.status(status),
	.status_menumask({15'h0, ~mod_turbo}), // H0: hide Turbo-only rotate/steering entries on Buck Rogers

	.ps2_key(ps2_key)
);

// Game strap: ioctl_index 1 is the mod byte MRA part gen_mra.py emits
// after every game's ROM regions (00 = Buck Rogers, 01 = Turbo). One RBF,
// selected at ROM-load time -- see docs/WORKPLAN_TURBO_GRAPHICS.md Step 1.
reg [7:0] mod_game;
always @(posedge clk_sys) if (ioctl_wr && ioctl_index == 16'd1) mod_game <= ioctl_dout;
wire mod_turbo = mod_game[0];

// DIP switches, MRA-sourced (mister-devel MkDocs_MiSTer, developer/mra):
// each game's .mra <switches> block streams up to 8 raw bytes over
// ioctl_index==254, addressed by ioctl_addr[2:0]. sw[0] = DSW1, sw[1] =
// DSW2, sw[2] = DSW3, matching the physical DIP bank numbering in
// docs/reference/turbo.cpp -- so dsw1/dsw2/turbo_dsw1/turbo_dsw2/
// turbo_dsw3 below are the raw bytes verbatim, no bit-inversion or
// reordering needed (the MRA's <dip ids="..."> order already encodes the
// correct raw value for each menu choice).
reg [7:0] sw[0:7];
always @(posedge clk_sys) if (ioctl_wr && ioctl_index == 16'd254) sw[ioctl_addr[2:0]] <= ioctl_dout;

// IN0/IN1/DSW1/DSW2 -- docs/PLAN.md phase 1 CPU/memory table, buckrog
// INPUT_PORTS_START in docs/reference/turbo.cpp. Joystick bit convention:
// [0]=Right [1]=Left [2]=Down [3]=Up are MiSTer's standard D-pad bits; the
// named buttons then start at [4] in "J1,..." order, so [4]=Fire,
// [5]=Accel Fast, [6]=Accel Slow, [7]=Start, [8]=Coin. All active-low
// (idle = 1), matching MAME's ACTIVE_LOW convention.
//
// P2's start and coin are read from joystick_1 at the SAME bit positions as
// P1's, which is the MiSTer convention -- taking them from spare joystick_0
// bits instead would put P2's start and coin on P1's controller.
//
// SERVICE1 (IN1 bit 5) and the TEST/service-mode line (IN1 bit 4) are tied
// inactive on purpose: neither had any observable effect in play, and a
// mapped button that does nothing is worse than no button. They are real
// hardware inputs (schematic sheet 4: I15=SERVICE, I14=TEST) and can be
// wired later if a use for them turns up.
//
// in0[5:4] are ACC.LO/ACC.HI (schematic sheet 4, PDF p32: two discrete
// opto-isolated lines on the control connector). The same two wires serve
// both accel modes -- SW2:2 only selects how the GAME reads them: fast/slow
// buttons in Button mode (the factory setting, wired here), or an inverted
// 2-bit Gray code from the pedal's opto pair in Pedal mode. No analog pedal
// source is wired, so selecting Pedal in the OSD leaves the throttle dead.
wire [7:0] in0 = {~joystick_0[3], ~joystick_0[2], ~joystick_0[6], ~joystick_0[5], ~joystick_1[7], 3'b111};
// NOTE in1[1:0]: MAME's IN1 is bit 0x01 = JOYSTICK_LEFT, bit 0x02 =
// JOYSTICK_RIGHT (turbo.cpp INPUT_PORTS_START(buckrog)), which is the
// OPPOSITE order from the MiSTer joystick convention above ([0]=Right,
// [1]=Left). These two bits were previously wired straight through in
// index order, which transposed the steering axis -- the ship (and with
// it the starfield's lateral sweep) banked the wrong way for a given
// stick direction. Cross them explicitly; do not "simplify" this back to
// [1],[0] order.
wire [7:0] in1 = {~joystick_0[8], ~joystick_1[8], 1'b1, 1'b1, ~joystick_0[7], ~joystick_0[4], ~joystick_0[0], ~joystick_0[1]};

// DSW assembly. Bit positions are buckrog's DSW1/DSW2 as read through
// port_2_r/port_3_r (the 4-bit bitswaps live in rtl/segavco.v, not here).
// Raw bytes straight from the MRA (see sw[] above) -- mra/buckrog.mra and
// mra/buckrogn.mra's <switches default="C0,92"> already encode the factory
// DSW1/DSW2 defaults (docs/reference/turbo.cpp), so no inversion is needed
// here the way the old status-bit CONF_STR options required.
wire [7:0] dsw1 = sw[0];
wire [7:0] dsw2 = sw[1];

// ------------------------------------------------------------------
// Turbo IN0/DSW1/DSW2/DSW3 and controls (docs/WORKPLAN_TURBO_GRAPHICS.md
// Step 7). turbo.cpp's IN0: bits[1:0] = pedal (inverted 2-bit Gray code),
// bit2 = gear shift (active-high, PORT_TOGGLE), bit3 = start1 (active-low),
// bit4 = service mode, bit5 = service1, bit6 = coin2, bit7 = coin1.
// Reuses Buck's Start/Coin bit positions (joystick_0[7]/[8]) so both games'
// buttons stay physically consistent; Gear Shift/Pedal are the two NEW J1
// entries appended above.
// ------------------------------------------------------------------
wire pedal_btn = joystick_0[10];
wire [7:0] pedal_raw = pedal_btn ? 8'hFF : 8'h00;
wire [7:0] pedal_gray = (pedal_raw >> 6) ^ (pedal_raw >> 7) ^ 8'h03;

// PORT_TOGGLE: the reported bit flips on each press (rising edge), not a
// plain pass-through -- matches turbo.cpp's gear shift lever, which stays
// in whichever gear it was last shifted to.
reg gear_toggle;
reg gear_btn_d;
always @(posedge clk_sys) begin
	gear_btn_d <= joystick_0[9];
	if (joystick_0[9] && !gear_btn_d) gear_toggle <= ~gear_toggle;
end

// bit6 (coin2) was previously ~joystick_1[5] (P2's Accel Fast button) --
// wrong bit entirely. Matches Buck's own in1[6] convention (~joystick_1[8],
// the same physical P2 coin button both games' cabinets share).
wire [7:0] turbo_in0 = {~joystick_0[8], ~joystick_1[8], 1'b1, 1'b1,
                         ~joystick_0[7], gear_toggle, pedal_gray[1:0]};

// DSW1/DSW2/DSW3 assembly. Raw bytes straight from the MRA (see sw[]
// above) -- mra/turbo.mra's <switches default="FB,FF,30"> already encodes
// the factory DSW1/DSW2/DSW3 defaults (docs/reference/turbo.cpp), so no
// inversion or reordering is needed the way the old status-bit CONF_STR
// options required.
wire [7:0] turbo_dsw1 = sw[0];
wire [7:0] turbo_dsw2 = sw[1];
wire [7:0] turbo_dsw3 = sw[2];

// Steering: turbo_state::analog_r() returns a DELTA (dial - last_analog),
// not an absolute position -- see rtl/io/steering_input.sv's header. The
// delta computation itself (the last_analog snapshot register, reset by
// writes to b800-bfff) lives in segavco.v, alongside the PPI3 port A read
// it feeds; this module only produces the free-running dial position.
reg vblank_d;
always @(posedge clk_sys) vblank_d <= VBlank;
wire ce_frame = VBlank & ~vblank_d;

// Tuned against the real Turbo steering mechanism, not just MAME's DIAL port:
// the schematic's LS191 counter is a x1 quadrature relative encoder (no HW
// accel/spring), and the photographed wheel-shaft gearing (~5:1) + encoder
// disk (~40 slots) puts one hardware count at roughly 45 degrees of wheel
// rotation -- i.e. the observed real-cabinet "~1/4 turn = ~1 car width"
// correction is only ~2 counts. RAMP_STEP=2/VEL_MAX=6 (post >>>1 shift) so
// the velocity ramp actually ramps instead of jumping straight to its
// ceiling: a 1-frame tap yields 1 count, climbing 1/2/3 over the first
// three held frames and capping at 3 counts/frame thereafter -- small taps
// stay small, and the 3-count/frame sustained ceiling (~135 degrees/frame)
// avoids constantly injecting the ~180-degree-plus swings a higher ceiling
// would imply, while still allowing full wheel rotation over a longer
// hold. POS_MAX=48 matches: the spring-return position mode's contribution
// (deflect>>>4) also tops out at 3 counts/frame, down from ~15 at the
// module's original default. Position mode remains a convenience
// alternative, not a cabinet-accurate model -- the real wheel has no
// spring return. ANALOG_SHIFT split out to 5 (SHIFT stays 4 for the dpad)
// so full analog-stick deflection (127>>>5 = 3 counts/frame) lines up with
// the same 3-count/frame ceiling as the dpad's sustained hold and the
// initial tap stays at 1 -- one coherent ceiling across all three digital
// input paths for the first hardware test.
wire [7:0] turbo_dial;
steering_input #(
	.RAMP_STEP(9'sd2), .VEL_MAX(9'sd6), .POS_MAX(9'sd48), .SHIFT(4), .ANALOG_SHIFT(5)
) u_steering
(
	.clk_sys(clk_sys), .reset(reset), .ce_frame(ce_frame),
	.dpad_pos_mode(status[10]), // OSD "D-Pad Steering": 0 = velocity ramp (default), 1 = position w/ spring-return
	.analog_x(joystick_l_analog_0[7:0]),
	.dpad_left(joystick_0[1]), .dpad_right(joystick_0[0]),
	.spinner(spinner_0),
	.wheel_pos(turbo_dial)
);

///////////////////////   CLOCKS   ///////////////////////////////

// 39.936 MHz core clock = 2x the Z80-3D board's 19.968 MHz master XTAL, per
// docs/PLAN.md "Clocking". Not exactly representable from the 50 MHz
// reference (the board's XTAL isn't a round number either), so
// rtl/pll/pll_0002.v targets Quartus's nearest legal PLL setting instead:
// 39,935,064 Hz, ~23 ppm low. Tighter than the crystal tolerance on real
// hardware, so this is not a meaningful source of timing error.
wire clk_sys;
wire pll_locked;
pll pll
(
	.refclk(CLK_50M),
	.rst(0),
	.outclk_0(clk_sys),
	.locked(pll_locked)
);

// NOTE: pll_locked is intentionally NOT gating reset. It was wired in during
// the hardening pass but never validated on real hardware, and the very
// first on-hardware test came back showing exactly the symptom a
// permanently-unlocked PLL would produce (core stuck in reset forever: ROM
// download over HPS still works since it's independent of core reset, but
// the CPU never executes) -- see docs/PLAN.md. Isolating the variable here
// until that's confirmed one way or the other.
// ioctl_download MUST be part of reset: the HPS streams the ROM blob into
// the CPUs' program ROM/RAM arrays over many thousands of cycles, and
// without holding the core in reset for that whole window both Z80s
// free-run executing partially-written memory, then are never reset once
// the download completes -- they simply continue from whatever arbitrary
// state they reached. That produces nondeterministic, boot-to-boot-varying
// corruption on real hardware (garbage sub-CPU state => wrong starfield
// direction//placement) which is structurally INVISIBLE in simulation,
// because sim/tb_z80_3d.cpp holds reset asserted across the entire
// download and releases it afterwards. Keep this in sync with that
// testbench behavior.
//
// (Distinct from the pll_locked experiment noted in docs/PLAN.md, which was
// removed because a never-locking PLL would hold the core in reset forever.
// ioctl_download is self-clearing when the transfer ends, so it cannot
// wedge the core the same way.)
wire reset = RESET | status[0] | buttons[1] | ioctl_download;

wire HBlank;
wire HSync;
wire VBlank;
wire VSync;
wire ce_pix;
wire [7:0] video_r, video_g, video_b;

// Sound board output, straight from the discrete model in rtl/audio.
wire signed [15:0] audio_l, audio_r;

segavco segavco
(
	.clk(clk_sys),
	.reset(reset),

	.mod_turbo(mod_turbo),

	.ioctl_download(ioctl_download),
	.ioctl_wr(ioctl_wr),
	.ioctl_addr(ioctl_addr),
	.ioctl_dout(ioctl_dout),
	.ioctl_index(ioctl_index),

	.in0(in0),
	.in1(in1),
	.dsw1(dsw1),
	.dsw2(dsw2),

	.turbo_in0(turbo_in0),
	.turbo_dsw1(turbo_dsw1),
	.turbo_dsw2(turbo_dsw2),
	.turbo_dsw3(turbo_dsw3),
	.turbo_dial(turbo_dial),

	.hblank(HBlank),
	.vblank(VBlank),
	.hsync(HSync),
	.vsync(VSync),
	.ce_pix(ce_pix),

	.video_r(video_r),
	.video_g(video_g),
	.video_b(video_b),
	.audio_l(audio_l),
	.audio_r(audio_r)
);

assign CLK_VIDEO = clk_sys;
assign CE_PIXEL = ce_pix;

assign VGA_DE = ~(HBlank | VBlank);
assign VGA_HS = HSync;
assign VGA_VS = VSync;
assign VGA_R  = video_r;
assign VGA_G  = video_g;
assign VGA_B  = video_b;

// Turbo's native raster is portrait (MAME ROT270); Buck Rogers/buckrogn is
// ROT0 and must never rotate. Writes a rotated copy of the already-final
// VGA_* picture into the DDRAM framebuffer for MiSTer's HDMI scaler path;
// VGA_* itself stays the raw, unrotated signal (see sys/arcade_video.v's
// screen_rotate header). rotate_ccw=1 is the ROT270-implies-90-degree-CCW
// starting hypothesis -- confirm on screen and flip if the picture comes
// out upside-down rather than sideways.
wire no_rotate = ~mod_turbo | status[6];
screen_rotate screen_rotate
(
	.CLK_VIDEO(CLK_VIDEO),
	.CE_PIXEL(CE_PIXEL),

	.VGA_R(VGA_R),
	.VGA_G(VGA_G),
	.VGA_B(VGA_B),
	.VGA_HS(VGA_HS),
	.VGA_VS(VGA_VS),
	.VGA_DE(VGA_DE),

	.rotate_ccw(1'b1),
	.no_rotate(no_rotate),
	.flip(1'b0),
	.video_rotated(),

	.FB_EN(FB_EN),
	.FB_FORMAT(FB_FORMAT),
	.FB_WIDTH(FB_WIDTH),
	.FB_HEIGHT(FB_HEIGHT),
	.FB_BASE(FB_BASE),
	.FB_STRIDE(FB_STRIDE),
	.FB_VBL(FB_VBL),
	.FB_LL(FB_LL),

	.DDRAM_CLK(DDRAM_CLK),
	.DDRAM_BUSY(DDRAM_BUSY),
	.DDRAM_BURSTCNT(DDRAM_BURSTCNT),
	.DDRAM_ADDR(DDRAM_ADDR),
	.DDRAM_DIN(DDRAM_DIN),
	.DDRAM_BE(DDRAM_BE),
	.DDRAM_WE(DDRAM_WE),
	.DDRAM_RD(DDRAM_RD)
);

reg  [26:0] act_cnt;
always @(posedge clk_sys) act_cnt <= act_cnt + 1'd1; 
assign LED_USER    = act_cnt[26]  ? act_cnt[25:18]  > act_cnt[7:0]  : act_cnt[25:18]  <= act_cnt[7:0];

endmodule
