// Turbo player-car channel (sheets D-8/11 and D-9/11).
//
//   D8 source/control: ACC(0-5) -> IC34/C110 speed ladder (64-code Thevenin
//   targets).  The MYCAR carrier is the IC6/C5 tone cell plus the IC6/C18+C19
//   sub cell through D7/D13, R79 and C76 (turbo_playercar_mycarsource.sv).  The
//   IC3/IC5/IC7 transient model (turbo_playercar_d8_transient.sv) only supplies
//   the MY CAR CONT / BSEL1 control side.  The hand-written "4391/2" blocks are
//   MB4391M dual-MC3340 VCAs.
//
//   D9 control/VCA: IC41 (74LS139) BSEL decoder selects exactly one of
//   BCONT0/1/2.  Each BCONT is a gated one-pole gain toward FULL (selected) or
//   MUTE (unselected).  BCONT0 drives the IC19-A/B VCA pair (MYCARQ.F/FM,
//   MYCARQ.W); BCONT1 drives IC18/IC28-upper (MYCAR1.F/FM, MYCAR1.W); BCONT2
//   drives IC28-lower (MYCAR.F/W/M via the R219/R220 loaded-feed split).  The
//   per-tap loading resistors of IC19/IC18 are not on the recovered sheets, so
//   MYCARQ.F/W (and MYCAR1.F/W) share one VCA product each.
//
//   SLF: switched by /MYCAR OFF (mycar_off_n, asserted at BSEL==3) through the
//   IC30/C108 W-bus transient.
//
// MULTIPLIER SHARING: every multiply (ladder smoothing, three BCONT gain
// updates, VCA products, two output DC-blocks; eleven ops per sample) is
// serialized through one shared_mul_lane via u_playercar_seq, the same
// P_IDLE/P_REQ/P_WAIT/P_READY idiom as turbo_crash_chan.sv's preamp sequencer.
// No two multiplies are chained combinationally; every op's operands and result
// are registered.
//
// DC-BLOCKING: the VCA outputs are DC-referenced node voltages; their output
// coupling caps (C114/C113/C112/C107/C69/C72/C66/C57/C61) are not modelled
// individually.  Two one-pole DC-blockers (~20 Hz) on the final F and W bus
// sums stand in for them so the audio taps are AC-centred.
module turbo_playercar_chan (
	input  logic               clk,
	input  logic               rst_n,
	input  logic                sample_ce,
	input  logic         [5:0] acc,      // ACC0-5, CN1 cn1_acc
	input  logic         [1:0] bsel,     // BSEL0-1, CN1 cn1_bsel -- IC41's select
	output logic signed [15:0] mycar_f_mix /* verilator public_flat */,   // BCONT2/IC28-lower (BSEL==2)
	output logic signed [15:0] mycar_w_mix /* verilator public_flat */,
	output logic signed [15:0] mycar_m_mix,
	output logic signed [15:0] mycarq_f_mix,  // BCONT0/IC19 (BSEL==0)
	output logic signed [15:0] mycarq_w_mix,
	output logic signed [15:0] mycar1_f_mix,  // BCONT1/IC18+IC28-upper (BSEL==1)
	output logic signed [15:0] mycar1_w_mix,
	output logic signed [15:0] slf_mix,
	output logic signed [15:0] dcblock_f_mix /* verilator public_flat */, // AC-coupled combined F (all 3 families)
	output logic signed [15:0] dcblock_w_mix /* verilator public_flat */, // AC-coupled combined W (all 3 families)
	output logic                mycar_off_n,  // /MYCAR OFF, active low (= bsel==3)
	output logic signed [15:0] dbg_source_raw,
	output logic signed [15:0] dbg_source_shaped,
	output logic         [5:0] dbg_acc,
	output logic         [1:0] dbg_bsel
);

	assign dbg_acc  = acc;
	assign dbg_bsel = bsel;
	assign mycar_off_n = !(bsel == 2'd3);

	// ---------------------------------------------------------------
	// ACC(0-63) -> IC6/C5 tone-cell step LUT.  On sheet D-8/11 the IC6 cell's
	// R28/R29 hang on the tap of the 4.7k/15k divider off IC3 pin 7, not on the
	// raw ladder buffer, so
	//   thresholds = 3.9735 V and 7.5199 V, dV = 3.5464 V
	//   R_eff = R28 + 1/(1/R31 - 1/R28) = 486 kOhm (R28=270k, R31=120k, C5=4700pF)
	//   f = V_bus/(2*dV*C5*R_eff) = 61.73 Hz/V * V_bus
	//   V_bus = V_ladder * 0.6727 (tap loaded by the three cells; 0.7614 unloaded)
	//   step = round((TH_HI-TH_LO)*(1+1/1.25)*f/clk_hz), clk_hz = 39,935,064;
	//          1.25 is R28/R31-1 (the ramp asymmetry, applied in mycarsource)
	// Generated by tools/gen_playercar_step_lut.py from the 64-code ladder
	// operating points; do not hand-edit.
	// ---------------------------------------------------------------
	localparam logic signed [39:0] STEP_LUT [0:63] = '{
		40'sd0, 40'sd21, 40'sd41, 40'sd62, 40'sd83, 40'sd104, 40'sd125, 40'sd146,
		40'sd166, 40'sd186, 40'sd208, 40'sd229, 40'sd250, 40'sd271, 40'sd292, 40'sd313,
		40'sd333, 40'sd353, 40'sd374, 40'sd395, 40'sd416, 40'sd437, 40'sd458, 40'sd480,
		40'sd500, 40'sd521, 40'sd542, 40'sd563, 40'sd584, 40'sd606, 40'sd628, 40'sd649,
		40'sd666, 40'sd687, 40'sd708, 40'sd730, 40'sd750, 40'sd771, 40'sd792, 40'sd813,
		40'sd834, 40'sd855, 40'sd877, 40'sd898, 40'sd919, 40'sd940, 40'sd962, 40'sd983,
		40'sd1004, 40'sd1025, 40'sd1046, 40'sd1067, 40'sd1088, 40'sd1109, 40'sd1131, 40'sd1153,
		40'sd1174, 40'sd1195, 40'sd1216, 40'sd1238, 40'sd1260, 40'sd1281, 40'sd1303, 40'sd1324
	};

	// IC6/TR5 sub-cell rate: 0.43 Hz/V (TR5's in-circuit VCE is not recoverable
	// from the sheet; the ideal-VCE bound would be 3.88 Hz/V).  Generated from the
	// same threshold swing and clock as STEP_LUT.
	localparam logic signed [39:0] SUB_STEP_LUT [0:63] = '{
		40'sd0, 40'sd2, 40'sd4, 40'sd5, 40'sd7, 40'sd9, 40'sd11, 40'sd13,
		40'sd14, 40'sd16, 40'sd18, 40'sd20, 40'sd21, 40'sd23, 40'sd25, 40'sd27,
		40'sd29, 40'sd30, 40'sd32, 40'sd34, 40'sd36, 40'sd38, 40'sd39, 40'sd41,
		40'sd43, 40'sd45, 40'sd47, 40'sd48, 40'sd50, 40'sd52, 40'sd54, 40'sd56,
		40'sd57, 40'sd59, 40'sd61, 40'sd63, 40'sd64, 40'sd66, 40'sd68, 40'sd70,
		40'sd72, 40'sd73, 40'sd75, 40'sd77, 40'sd79, 40'sd81, 40'sd83, 40'sd84,
		40'sd86, 40'sd88, 40'sd90, 40'sd92, 40'sd93, 40'sd95, 40'sd97, 40'sd99,
		40'sd101, 40'sd103, 40'sd104, 40'sd106, 40'sd108, 40'sd110, 40'sd112, 40'sd114
	};

	// The same IC34/C110 ladder as STEP_LUT, as a voltage-domain table (Q12 volts)
	// for the IC3-A -> MYCAR CONT path.  IC3-A's LM324 output is clamped to the
	// 0..10.5-V single-supply range before the 4.7k/15k divider on D8.
	localparam logic signed [20:0] V_LADDER_LUT_Q12 [0:63] = '{
		21'sd0, 21'sd757, 21'sd1514, 21'sd2279, 21'sd3028, 21'sd3792, 21'sd4558, 21'sd5330,
		21'sd6057, 21'sd6820, 21'sd7585, 21'sd8356, 21'sd9118, 21'sd9889, 21'sd10663, 21'sd11442,
		21'sd12121, 21'sd12885, 21'sd13649, 21'sd14421, 21'sd15180, 21'sd15950, 21'sd16724, 21'sd17503,
		21'sd18252, 21'sd19022, 21'sd19794, 21'sd20572, 21'sd21345, 21'sd22122, 21'sd22904, 21'sd23690,
		21'sd24309, 21'sd25074, 21'sd25840, 21'sd26614, 21'sd27373, 21'sd28146, 21'sd28922, 21'sd29702,
		21'sd30448, 21'sd31220, 21'sd31993, 21'sd32774, 21'sd33547, 21'sd34326, 21'sd35110, 21'sd35897,
		21'sd36629, 21'sd37401, 21'sd38174, 21'sd38955, 21'sd39725, 21'sd40504, 21'sd41287, 21'sd42075,
		21'sd42844, 21'sd43622, 21'sd44404, 21'sd45191, 21'sd45975, 21'sd46760, 21'sd47552, 21'sd48346
	};

	// BEGIN GENERATED IC17 TABLES (tools/gen_playercar_ic17_tables.py) -- do not hand-edit
	// IC7 relaxation cell step LUT: f = 73.4 Hz/V_bus (board population, C = 7.007 nF), V_bus = V_ladder*0.6727 (loaded 4.7k/15k tap)
	localparam logic signed [39:0] IC7_STEP_LUT [0:63] = '{
		40'sd0, 40'sd25, 40'sd50, 40'sd75, 40'sd100, 40'sd125, 40'sd150, 40'sd175,
		40'sd199, 40'sd224, 40'sd249, 40'sd275, 40'sd300, 40'sd325, 40'sd351, 40'sd376,
		40'sd398, 40'sd424, 40'sd449, 40'sd474, 40'sd499, 40'sd524, 40'sd550, 40'sd575,
		40'sd600, 40'sd625, 40'sd651, 40'sd676, 40'sd702, 40'sd727, 40'sd753, 40'sd779,
		40'sd799, 40'sd824, 40'sd849, 40'sd875, 40'sd900, 40'sd925, 40'sd951, 40'sd976,
		40'sd1001, 40'sd1026, 40'sd1052, 40'sd1077, 40'sd1103, 40'sd1128, 40'sd1154, 40'sd1180,
		40'sd1204, 40'sd1229, 40'sd1255, 40'sd1280, 40'sd1306, 40'sd1331, 40'sd1357, 40'sd1383,
		40'sd1408, 40'sd1434, 40'sd1460, 40'sd1485, 40'sd1511, 40'sd1537, 40'sd1563, 40'sd1589
	};
	// IC7-C + input DC (bus via 10k, D5/D6 clamp to the 3.92-V R38/R39 midpoint), Q12 volts,
	// indexed by v_ladder_q12 >> 8 (1/16 V of ladder voltage)
	localparam logic signed [20:0] CLAMP_DC_LUT_Q12 [0:191] = '{
		21'sd13331, 21'sd13338, 21'sd13344, 21'sd13350, 21'sd13356, 21'sd13363, 21'sd13369, 21'sd13376,
		21'sd13382, 21'sd13389, 21'sd13395, 21'sd13402, 21'sd13408, 21'sd13415, 21'sd13422, 21'sd13428,
		21'sd13435, 21'sd13442, 21'sd13449, 21'sd13456, 21'sd13463, 21'sd13470, 21'sd13477, 21'sd13484,
		21'sd13491, 21'sd13499, 21'sd13506, 21'sd13513, 21'sd13521, 21'sd13528, 21'sd13536, 21'sd13544,
		21'sd13551, 21'sd13559, 21'sd13567, 21'sd13575, 21'sd13583, 21'sd13592, 21'sd13600, 21'sd13608,
		21'sd13617, 21'sd13625, 21'sd13634, 21'sd13643, 21'sd13652, 21'sd13661, 21'sd13671, 21'sd13680,
		21'sd13690, 21'sd13700, 21'sd13710, 21'sd13720, 21'sd13730, 21'sd13741, 21'sd13752, 21'sd13763,
		21'sd13774, 21'sd13786, 21'sd13798, 21'sd13810, 21'sd13823, 21'sd13836, 21'sd13850, 21'sd13864,
		21'sd13879, 21'sd13894, 21'sd13910, 21'sd13926, 21'sd13944, 21'sd13962, 21'sd13982, 21'sd14002,
		21'sd14024, 21'sd14048, 21'sd14074, 21'sd14102, 21'sd14132, 21'sd14167, 21'sd14205, 21'sd14250,
		21'sd14301, 21'sd17684, 21'sd17797, 21'sd17871, 21'sd17925, 21'sd17969, 21'sd18006, 21'sd18039,
		21'sd18067, 21'sd18093, 21'sd18116, 21'sd18137, 21'sd18157, 21'sd13952, 21'sd13972, 21'sd13992,
		21'sd14014, 21'sd14039, 21'sd14065, 21'sd14096, 21'sd14130, 21'sd14170, 21'sd14218, 21'sd14281,
		21'sd14369, 21'sd14527, 21'sd17844, 21'sd17891, 21'sd17933, 21'sd17969, 21'sd18002, 21'sd18031,
		21'sd18058, 21'sd18083, 21'sd18106, 21'sd18127, 21'sd18147, 21'sd18166, 21'sd18184, 21'sd18201,
		21'sd18217, 21'sd18233, 21'sd18248, 21'sd18262, 21'sd18276, 21'sd18289, 21'sd18302, 21'sd18315,
		21'sd18327, 21'sd18339, 21'sd18350, 21'sd18362, 21'sd18373, 21'sd18383, 21'sd18394, 21'sd18404,
		21'sd18414, 21'sd18424, 21'sd18434, 21'sd18444, 21'sd18453, 21'sd18462, 21'sd18471, 21'sd18480,
		21'sd18489, 21'sd18498, 21'sd18506, 21'sd18515, 21'sd18523, 21'sd18532, 21'sd18540, 21'sd18548,
		21'sd18556, 21'sd18564, 21'sd18571, 21'sd18579, 21'sd18587, 21'sd18594, 21'sd18602, 21'sd18609,
		21'sd18617, 21'sd18624, 21'sd18631, 21'sd18638, 21'sd18646, 21'sd18653, 21'sd18660, 21'sd18667,
		21'sd18674, 21'sd18680, 21'sd18687, 21'sd18694, 21'sd18701, 21'sd18707, 21'sd18714, 21'sd18721,
		21'sd18727, 21'sd18734, 21'sd18740, 21'sd18747, 21'sd18753, 21'sd18759, 21'sd18766, 21'sd18772,
		21'sd18778, 21'sd18785, 21'sd18791, 21'sd18797, 21'sd18803, 21'sd18809, 21'sd18815, 21'sd18821
	};
	// IC17 MC3340 relative gain vs CONT voltage, Q16, 1/64-V bins from 3.0 V
	localparam logic signed [26:0] GAIN17_LUT_Q16 [0:192] = '{
		27'sd65536, 27'sd64722, 27'sd63919, 27'sd63126, 27'sd62342, 27'sd61313, 27'sd60302, 27'sd59307,
		27'sd58328, 27'sd57045, 27'sd55790, 27'sd54562, 27'sd53362, 27'sd51806, 27'sd50296, 27'sd48829,
		27'sd47406, 27'sd45382, 27'sd43444, 27'sd41589, 27'sd39813, 27'sd36627, 27'sd33696, 27'sd31000,
		27'sd28519, 27'sd25784, 27'sd23311, 27'sd21075, 27'sd19054, 27'sd17226, 27'sd15574, 27'sd14080,
		27'sd12730, 27'sd11509, 27'sd10405, 27'sd9407, 27'sd8505, 27'sd7811, 27'sd7174, 27'sd6589,
		27'sd6051, 27'sd5593, 27'sd5170, 27'sd4779, 27'sd4418, 27'sd4088, 27'sd3784, 27'sd3502,
		27'sd3241, 27'sd3004, 27'sd2784, 27'sd2580, 27'sd2391, 27'sd2219, 27'sd2059, 27'sd1910,
		27'sd1772, 27'sd1646, 27'sd1530, 27'sd1421, 27'sd1320, 27'sd1228, 27'sd1142, 27'sd1062,
		27'sd988, 27'sd920, 27'sd857, 27'sd798, 27'sd743, 27'sd692, 27'sd645, 27'sd602,
		27'sd561, 27'sd523, 27'sd488, 27'sd456, 27'sd425, 27'sd397, 27'sd371, 27'sd347,
		27'sd324, 27'sd303, 27'sd283, 27'sd265, 27'sd248, 27'sd232, 27'sd217, 27'sd203,
		27'sd190, 27'sd178, 27'sd167, 27'sd156, 27'sd146, 27'sd137, 27'sd129, 27'sd121,
		27'sd113, 27'sd106, 27'sd100, 27'sd94, 27'sd88, 27'sd83, 27'sd78, 27'sd73,
		27'sd68, 27'sd64, 27'sd60, 27'sd57, 27'sd53, 27'sd50, 27'sd47, 27'sd45,
		27'sd42, 27'sd39, 27'sd37, 27'sd35, 27'sd33, 27'sd31, 27'sd29, 27'sd28,
		27'sd26, 27'sd25, 27'sd23, 27'sd22, 27'sd21, 27'sd19, 27'sd18, 27'sd17,
		27'sd16, 27'sd15, 27'sd15, 27'sd14, 27'sd13, 27'sd12, 27'sd12, 27'sd11,
		27'sd10, 27'sd10, 27'sd9, 27'sd9, 27'sd8, 27'sd8, 27'sd7, 27'sd7,
		27'sd7, 27'sd6, 27'sd6, 27'sd6, 27'sd5, 27'sd5, 27'sd5, 27'sd5,
		27'sd4, 27'sd4, 27'sd4, 27'sd4, 27'sd4, 27'sd3, 27'sd3, 27'sd3,
		27'sd3, 27'sd3, 27'sd3, 27'sd3, 27'sd2, 27'sd2, 27'sd2, 27'sd2,
		27'sd2, 27'sd2, 27'sd2, 27'sd2, 27'sd2, 27'sd2, 27'sd2, 27'sd2,
		27'sd2, 27'sd2, 27'sd2, 27'sd2, 27'sd2, 27'sd2, 27'sd2, 27'sd2,
		27'sd2, 27'sd2, 27'sd2, 27'sd2, 27'sd2, 27'sd2, 27'sd2, 27'sd2,
		27'sd2
	};
	// END GENERATED IC17 TABLES

	wire signed [39:0] step_target = STEP_LUT[acc];
	wire signed [39:0] sub_step_target = SUB_STEP_LUT[acc];
	wire signed [39:0] ic7_step_target = IC7_STEP_LUT[acc];

	// ACC-ladder C110 one-pole smoothing.  The Thevenin resistance varies only
	// 50.00k-50.73k across all 64 codes, so one 50k*1uF = 50 ms tau is a tight fit.
	// Filtering in the step domain is exact up to rounding because step = k1 + k2*V
	// is affine in V.  For x[n+1] = x[n] + beta*(target-x[n]), beta = 1-alpha.
	localparam logic signed [26:0] LADDER_B_Q16 = 27'sd27; // 1-exp(-1/(fs*50ms))
	// The state is kept fractional: the VCO step is only a few hundred Q24 counts
	// and beta is 27/65536, so an integer-only state would round every update to
	// zero.  The oscillator consumes the integer part.
	logic signed [55:0] step_smoothed_q16;
	logic signed [55:0] sub_step_smoothed_q16;
	logic signed [55:0] ic7_step_smoothed_q16;
	// C110-smoothed ACC ladder voltage, Q12 volts with 16 fractional bits, updated
	// in the same serialized pass as step_smoothed.
	logic signed [55:0] v_ladder_smoothed_q16;
	// Visible to the behavioral bench.
	logic signed [39:0] step_smoothed /* verilator public_flat */;
	logic signed [39:0] sub_step_smoothed /* verilator public_flat */;
	always_comb step_smoothed = step_smoothed_q16 >>> 16;
	always_comb sub_step_smoothed = sub_step_smoothed_q16 >>> 16;
	logic signed [39:0] ic7_step_smoothed /* verilator public_flat */;
	always_comb ic7_step_smoothed = ic7_step_smoothed_q16 >>> 16;

	wire signed [55:0] v_ladder_target_q16 =
		$signed({{19{V_LADDER_LUT_Q12[acc][20]}}, V_LADDER_LUT_Q12[acc], 16'd0});
	wire signed [55:0] v_ladder_delta_q16 =
		v_ladder_target_q16 - v_ladder_smoothed_q16;
	// 27/65536 = (32-4-2+1)/65536: shift/add form of the C110 beta.
	wire signed [55:0] v_ladder_beta_step_q16 =
		(v_ladder_delta_q16 >>> 11) -
		(v_ladder_delta_q16 >>> 14) -
		(v_ladder_delta_q16 >>> 15) +
		(v_ladder_delta_q16 >>> 16);

	wire signed [55:0] sub_step_target_q16 = $signed({sub_step_target, 16'd0});
	wire signed [55:0] sub_step_delta_q16 =
		sub_step_target_q16 - sub_step_smoothed_q16;
	wire signed [55:0] sub_step_beta_step_q16 =
		(sub_step_delta_q16 >>> 11) -
		(sub_step_delta_q16 >>> 14) -
		(sub_step_delta_q16 >>> 15) +
		(sub_step_delta_q16 >>> 16);

	wire signed [55:0] ic7_step_target_q16 = $signed({ic7_step_target, 16'd0});
	wire signed [55:0] ic7_step_delta_q16 =
		ic7_step_target_q16 - ic7_step_smoothed_q16;
	wire signed [55:0] ic7_step_beta_step_q16 =
		(ic7_step_delta_q16 >>> 11) -
		(ic7_step_delta_q16 >>> 14) -
		(ic7_step_delta_q16 >>> 15) +
		(ic7_step_delta_q16 >>> 16);

	function automatic logic signed [55:0] clamp_speed_q12(
		input logic signed [55:0] value
	);
		begin
			if (value < 56'sd0)
				clamp_speed_q12 = 56'sd0;
			else if (value > 56'sd43008) // 10.5 V * 4096
				clamp_speed_q12 = 56'sd43008;
			else
				clamp_speed_q12 = value;
		end
	endfunction

	// Ladder-side tap of the IC3-A divider.  The labelled MY CAR CONT wire is the
	// IC7-A input after the IC5-C/loop path (the BSEL1 audio family is fed by the
	// d8_transient loop tap), so this is kept as a diagnostic only.
	wire signed [55:0] ic3_speed_q12 =
		clamp_speed_q12(v_ladder_smoothed_q16 >>> 16);
	wire signed [55:0] mycar_cont_div_q12 =
		(ic3_speed_q12 >>> 1) +
		(ic3_speed_q12 >>> 2) +
		(ic3_speed_q12 >>> 6) -
		(ic3_speed_q12 >>> 8);
	logic signed [20:0] mycar_cont_q12 /* verilator public_flat */;
	always_comb begin
		if (mycar_cont_div_q12 < 56'sd0)
			mycar_cont_q12 = 21'sd0;
		else if (mycar_cont_div_q12 > 56'sd43008)
			mycar_cont_q12 = 21'sd43008;
		else
			mycar_cont_q12 = mycar_cont_div_q12[20:0];
	end

	// ---------------------------------------------------------------
	// MYCAR source: IC6/C5 tone + IC6/C18+C19 sub, D7/D13, R79/C76.  The
	// IC3/IC5/IC7 transient model feeds only the MY CAR CONT/BSEL1 control family.
	// ---------------------------------------------------------------
	logic signed [15:0] pc_tone_raw /* verilator public_flat */;
	logic signed [15:0] pc_source_shaped;
	logic signed [15:0] pc_sub_raw;
	logic signed [15:0] pc_mycar_cont_ac /* verilator public_flat */;
	logic signed [15:0] pc_n_bout_ac;
	logic signed [20:0] pc_tone_v_q12;
	logic signed [20:0] pc_sub_v_q12;
	logic signed [20:0] pc_node_v_q12;
	logic signed [20:0] pc_ic7_v_q12;

	function automatic logic signed [15:0] pc_q12_to_sat16(
		input logic signed [55:0] value
	);
		logic signed [55:0] shifted;
		begin
			shifted = value;
			if (shifted > 56'sd32767)
				pc_q12_to_sat16 = 16'sd32767;
			else if (shifted < -56'sd32768)
				pc_q12_to_sat16 = 16'sh8000;
			else
				pc_q12_to_sat16 = shifted[15:0];
		end
	endfunction

	// N_SRC is the ladder voltage; the transient model's source_in is the AC
	// departure from its 6-V reference.
	wire signed [55:0] pc_n_src_ac_q12 =
		$signed(v_ladder_smoothed_q16 >>> 16) - 56'sd24576;
	wire signed [15:0] pc_n_src_ac = pc_q12_to_sat16(pc_n_src_ac_q12);
	logic signed [20:0] pc_mycar_cont_v_q12;
	logic signed [20:0] pc_n_bout_v_q12;
	turbo_playercar_d8_transient_pipe u_d8_transient (
		.clk             (clk),
		.rst_n           (rst_n),
		.sample_ce       (sample_ce),
		.source_in       (pc_n_src_ac),
		.n_bout_ac       (pc_n_bout_ac),
		.mycar_cont_ac   (pc_mycar_cont_ac),
		.n_bout_v_q12    (pc_n_bout_v_q12),
		.mycar_cont_v_q12(pc_mycar_cont_v_q12)
	);

	turbo_playercar_mycarsource u_mycarsource (
		.clk          (clk),
		.rst_n        (rst_n),
		.sample_ce    (sample_ce),
		.tone_step_q24(step_smoothed),
		.sub_step_q24 (sub_step_smoothed),
		.ic7_step_q24 (ic7_step_smoothed),
		.tone_ac      (pc_tone_raw),
		.sub_ac       (pc_sub_raw),
		.node_ac      (pc_source_shaped),
		.tone_v_q12   (pc_tone_v_q12),
		.sub_v_q12    (pc_sub_v_q12),
		.node_v_q12   (pc_node_v_q12),
		.ic7_v_q12    (pc_ic7_v_q12)
	);

	assign dbg_source_raw    = pc_tone_raw;
	assign dbg_source_shaped = pc_source_shaped;

	// The shared node is already the centred Q12 AC departure at C76/IC17.
	logic signed [15:0] player_source_pipe;
	logic signed [15:0] player_tone_pipe;
	wire signed [15:0] pc_tone = player_source_pipe;

	// ---------------------------------------------------------------
	// IC17 (upper half, MB4391 = MC3340) gain on the MYCAR carrier.  The
	// D7/D13/R79 node reaches IC17 pin 5 (IN) through C76; IC17's CONT pin is driven
	// by IC7-C.  IC7-C's + input is the bus (V_ladder * 0.6727) through 10k, clamped
	// by D5/D6 to the 3.92-V R38/R39 midpoint; its - input takes the IC7 cell's
	// triangle through C6/R36 (AC only) with R35=R36, so
	//     V_CONT = V_clampDC + (mean - V_ic7)     (unity-gain inversion of the AC)
	// The MC3340 law is flat below ~3.1 V and falls ~40 dB/V above it, so the
	// carrier is gated at the IC7-cell rate.
	// ---------------------------------------------------------------
	localparam logic signed [20:0] IC17_MEAN_Q12 = 21'sd23538;   // (3.9735+7.5199)/2 V
	wire [7:0] ic17_clamp_idx = ic3_speed_q12[15:8];             // 1/16-V bins of V_ladder
	wire signed [20:0] ic17_clamp_dc_q12 = CLAMP_DC_LUT_Q12[ic17_clamp_idx];
	wire signed [22:0] ic17_v2_q12 =
		$signed({{2{ic17_clamp_dc_q12[20]}}, ic17_clamp_dc_q12}) +
		$signed({{2{IC17_MEAN_Q12[20]}}, IC17_MEAN_Q12}) -
		$signed({{2{pc_ic7_v_q12[20]}}, pc_ic7_v_q12});
	wire signed [22:0] ic17_rel_q12 = ic17_v2_q12 - 23'sd12288;  // volts above 3.0 V
	wire signed [22:0] ic17_idx_wide = ic17_rel_q12 >>> 6;       // 1/64-V bins
	wire [7:0] ic17_gain_idx = (ic17_rel_q12 < 23'sd0) ? 8'd0 :
							   (ic17_idx_wide > 23'sd192) ? 8'd192 :
							   ic17_idx_wide[7:0];
	logic signed [26:0] ic17_gain_q16 /* verilator public_flat */;
	logic signed [15:0] pc_carrier_gated_next;
	always_ff @(posedge clk) begin
		if (!rst_n)
			ic17_gain_q16 <= 27'sd65536;
		else if (sample_ce)
			ic17_gain_q16 <= GAIN17_LUT_Q16[ic17_gain_idx];
	end

	// ---------------------------------------------------------------
	// D9 family conditioning.  BSEL0 passes through the IC20/IC21 4.7-nF shaping
	// network and BSEL1 through the IC23-D -> IC24-A chain before its VCAs.  Only
	// resistor ratios and capacitor behaviour supported by the traces are modelled.
	//
	// BSEL0: IC20-A R154/R155 = 22k/100k (inverting), IC20-B R159/R158 = 10k/10k
	// (second inversion): net +0.22, as 7/32 = 0.21875.  C75 = 4.7 nF with the ~10k
	// IC20 source leg has alpha ~= 0.35 at 48 kHz (3/8).  C93 is the following
	// 4.7-nF/100-kOhm IC21 pole (tau ~= 470 us, alpha ~= 2842/65536), kept as a
	// second state.
	// BSEL1 F/FM: IC23-D R166=R167=10k (unity inverting), then IC24-A R333=10k /
	// R170=12k (inverting, 1.2): net AC gain 1.2, as 19/16 = 1.1875 (no DSP).
	//
	// BSEL1 W: a distinct IC24-B/C branch.  C155-coupled input through R196=10k,
	// R194=10k feedback around IC24-B, then a second R194=10k into IC24-C with
	// R170=12k feedback, before C102/IC28-upper.  The two inversions cancel; nominal
	// gain 1.2.  C155 = 1 uF * 10k gives a ~15.9-Hz high-pass.  C97 is the IC24-B
	// bias capacitor.  IC38's 555 is control/debug only and is not injected into the
	// carrier.
	logic signed [15:0] d9_bsel0_src_fast;
	logic signed [15:0] d9_bsel0_src;
	logic signed [15:0] d9_bsel1_src_a /* verilator public_flat */;
	logic signed [15:0] d9_bsel1_src_b /* verilator public_flat */;
	logic signed [15:0] d9_bsel1_src_w /* verilator public_flat */;
	logic signed [15:0] d9_bsel1_w_prev_in;
	logic signed [39:0] d9_bsel1_w_hp_q16;
	// IC38 (555, 5 V) timing network, D-9/11: R270 51k from 5 V to DIS (pin 7), 51k
	// from DIS to the timing node (pins 2/6), C = 15 uF.  Charge through 102k*15uF =
	// 1.53 s toward 5 V, discharge through 51k*15uF = 0.765 s toward 0 V, between
	// CON/2 and CON.  CON (pin 5) is the IC23-A follower of (V_MYCARCONT + 12)/4,
	// mean 3.98 V; its 385 Hz ripple is not modelled.
	// IC23-B buffers the timing node; C155 1 uF + R196 10k (16 Hz corner) make a
	// differentiator: d = R196*C155*dV/dt = 10 ms * dV/dt, i.e. 480 samples * a *
	// (5 - v) while charging, -480 * a' * v while discharging.
	// IC24-B then gives CONT_F = V_BCONT1 - d and IC24-C gives CONT_W = V_BCONT1 + 1.2 d.
	// v is volts in Q24.  a = 1/(48000*1.53) ~ 2^-16 - 2^-19 + 2^-22,
	// a' = 1/(48000*0.765) ~ 2^-15 - 2^-18 + 2^-21.
	localparam logic signed [31:0] D9_555_CON_Q24  = 32'sd66765722;   // 3.98 V
	localparam logic signed [31:0] D9_555_LOWTH_Q24 = 32'sd33382861;  // 1.99 V
	localparam logic signed [31:0] D9_555_VCC_Q24  = 32'sd83886080;   // 5.0 V
	logic signed [31:0] d9_555_v;                       // timing-node voltage, Q24 V
	logic               d9_555_out /* verilator public_flat */;   // 1 = charging
	wire  signed [31:0] d9_555_up   = D9_555_VCC_Q24 - d9_555_v;
	wire  signed [31:0] d9_555_step_up = (d9_555_up >>> 16) - (d9_555_up >>> 19) + (d9_555_up >>> 22);
	wire  signed [31:0] d9_555_step_dn = (d9_555_v >>> 15) - (d9_555_v >>> 18) + (d9_555_v >>> 21);
	// d in Q24 volts: charging (5-v)*0.006592 (2^-8+2^-9+2^-11+2^-12), discharging -v*0.01318 (2^-7+2^-8+2^-10+2^-11)
	wire  signed [31:0] d9_d_up = (d9_555_up >>> 8) + (d9_555_up >>> 9) + (d9_555_up >>> 11) + (d9_555_up >>> 12);
	wire  signed [31:0] d9_d_dn = (d9_555_v  >>> 7) + (d9_555_v  >>> 8) + (d9_555_v  >>> 10) + (d9_555_v  >>> 11);
	wire  signed [31:0] d9_ramp_d_q24 = d9_555_out ? d9_d_up : -d9_d_dn;   // ramp-derived d, volts Q24

	always_ff @(posedge clk) begin
		if (!rst_n) begin
			d9_555_v   <= D9_555_LOWTH_Q24;
			d9_555_out <= 1'b1;
		end
		else if (sample_ce) begin
			if (d9_555_out) begin
				d9_555_v <= d9_555_v + d9_555_step_up;
				if (d9_555_v >= D9_555_CON_Q24) d9_555_out <= 1'b0;
			end
			else begin
				d9_555_v <= d9_555_v - d9_555_step_dn;
				if (d9_555_v <= D9_555_LOWTH_Q24) d9_555_out <= 1'b1;
			end
		end
	end

	// BSEL1 audio comes from the MY CAR CONT family, not the MYCAR carrier.  The
	// 555 output is control-only (it reaches the IC23 section-B/C155 network); the
	// traced 555 timing is kept as a public diagnostic.  The IC23/IC24 loading is
	// represented by bounded RC states below.
	wire signed [15:0] d9_bsel1_target = pc_mycar_cont_ac;
	function automatic logic signed [15:0] d9_gain22_sat(
		input logic signed [15:0] value
	);
		logic signed [17:0] ext;
		logic signed [17:0] result;
		begin
			// 7/32 = 1/4 - 1/32: shift/add form of the IC20-A/B net gain 22k/100k; the
			// two inversions make the AC sign positive.
			ext = {{2{value[15]}}, value};
			result = (ext >>> 2) - (ext >>> 5);
			if (result > 18'sd32767)
				d9_gain22_sat = 16'sd32767;
			else if (result < -18'sd32768)
				d9_gain22_sat = 16'sh8000;
			else
				d9_gain22_sat = result[15:0];
		end
	endfunction
	wire signed [15:0] d9_bsel0_target = d9_gain22_sat(pc_tone);
	wire signed [16:0] d9_bsel0_delta_fast =
		$signed({d9_bsel0_src_fast[15], d9_bsel0_src_fast}) -
		$signed({d9_bsel0_target[15], d9_bsel0_target});
	wire signed [16:0] d9_bsel0_delta_slow =
		$signed({d9_bsel0_src[15], d9_bsel0_src}) -
		$signed({d9_bsel0_src_fast[15], d9_bsel0_src_fast});
	// 2842/65536: the nominal C93 pole (the exponential corner rounds to 2842 at 47.999 kHz).
	wire signed [16:0] d9_bsel0_alpha_delta_slow =
		(d9_bsel0_delta_slow >>> 5) +
		(d9_bsel0_delta_slow >>> 7) +
		(d9_bsel0_delta_slow >>> 8) +
		(d9_bsel0_delta_slow >>> 12) +
		(d9_bsel0_delta_slow >>> 13) +
		(d9_bsel0_delta_slow >>> 15);

	function automatic logic signed [15:0] d9_src_add(
		input logic signed [15:0] base,
		input logic signed [16:0] delta
	);
		logic signed [17:0] sum;
		begin
			sum = $signed({base[15], base}) + $signed({delta[16], delta});
			if (sum > 18'sd32767)
				d9_src_add = 16'sd32767;
			else if (sum < -18'sd32768)
				d9_src_add = 16'sh8000;
			else
				d9_src_add = sum[15:0];
		end
	endfunction

	function automatic logic signed [15:0] d9_negate_sat(
		input logic signed [15:0] value
	);
		logic signed [16:0] wide;
		begin
			wide = -$signed({value[15], value});
			if (wide > 17'sd32767)
				d9_negate_sat = 16'sd32767;
			else if (wide < -17'sd32768)
				d9_negate_sat = 16'sh8000;
			else
				d9_negate_sat = wide[15:0];
		end
	endfunction

	function automatic logic signed [15:0] d9_gain12_sat(
		input logic signed [15:0] value
	);
		logic signed [19:0] ext;
		logic signed [19:0] result;
		begin
			// 19/16 = 1 + 1/4 - 1/16: shift/add form of the IC24-A gain 12k/10k = 1.2.
			ext = {{4{value[15]}}, value};
			result = ext + (ext >>> 2) - (ext >>> 4);
			if (result > 20'sd32767)
				d9_gain12_sat = 16'sd32767;
			else if (result < -20'sd32768)
				d9_gain12_sat = 16'sh8000;
			else
				d9_gain12_sat = result[15:0];
		end
	endfunction

	wire signed [15:0] d9_bsel1_stage_a = d9_negate_sat(d9_bsel1_target);
	wire signed [15:0] d9_bsel1_stage_b = d9_gain12_sat(d9_bsel1_stage_a);

	// C155/R196 high-pass for the IC24-B/C W branch: alpha_loss = 1-exp(-1/(10k*1uF*48k))
	// ~ 136/65536, expressed as 128+8 so no multiplier lane is used.
	wire signed [39:0] d9_bsel1_w_delta_q16 =
		($signed({{23{d9_bsel1_target[15]}}, d9_bsel1_target}) -
		 $signed({{23{d9_bsel1_w_prev_in[15]}}, d9_bsel1_w_prev_in})) <<< 16;
	wire signed [39:0] d9_bsel1_w_hp_sum_q16 =
		d9_bsel1_w_hp_q16 + d9_bsel1_w_delta_q16;
	wire signed [39:0] d9_bsel1_w_hp_loss_q16 =
		(d9_bsel1_w_hp_sum_q16 >>> 9) +
		(d9_bsel1_w_hp_sum_q16 >>> 13);
	wire signed [39:0] d9_bsel1_w_hp_next_q16 =
		d9_bsel1_w_hp_sum_q16 - d9_bsel1_w_hp_loss_q16;

	function automatic logic signed [15:0] d9_q16_to_sat16(
		input logic signed [39:0] value
	);
		logic signed [39:0] shifted;
		begin
			shifted = value >>> 16;
			if (shifted > 40'sd32767)
				d9_q16_to_sat16 = 16'sd32767;
			else if (shifted < -40'sd32768)
				d9_q16_to_sat16 = 16'sh8000;
			else
				d9_q16_to_sat16 = shifted[15:0];
		end
	endfunction

	wire signed [15:0] d9_bsel1_w_hp =
		d9_q16_to_sat16(d9_bsel1_w_hp_next_q16);
	wire signed [15:0] d9_bsel1_stage_w = d9_gain12_sat(d9_bsel1_w_hp);

	// ---------------------------------------------------------------
	// BSEL1 (tunnel) audio, D-9/11.  IC18 (F) and IC28-upper (W) both take the IC21
	// output through C84/C102.  Audio chain from the MYCAR net:
	//   IC20-A  inverting, R154/R155 = 22k/100k                 gain 0.22
	//   IC20-B + IC21-A: b = x - u with an integrator x = -b/(s*R160*C75), so
	//        x = u/(1+s*tau) : first-order low-pass, tau = 10k*4.7n = 47 us
	//        (3.39 kHz), unity gain (IC20-B's high-pass output b goes to BSEL0)
	//   IC21-B  Sallen-Key low-pass, R185=R186=100k, C93=C94=4.7n, gain 2
	//        (R2/R2 = 2.2k/2.2k): f0 = 1/(2*pi*100k*4.7n) = 338.6 Hz, Q = 1
	//   IC21-C/D inverting, R182 = 22k in, R180+R181 = 8.2k+1k feedback   gain 0.418
	// Net DC gain 0.22*2*0.418 = 0.184 (the three inversions cancel).
	// The Sallen-Key stage is a Chamberlin state-variable low-pass
	// (f = 2*sin(pi*f0/fs) = 0.04443, q = 1/Q = 1) with shift/add constants:
	// f = 1/32+1/128+1/256+1/1024+1/2048, 0.1839 ~ 47/256.
	// The 555 reaches the CONT amplifiers only through the 16-Hz C155/R196 high-pass,
	// giving ~19 mV of CONT ripple (< 1 dB tremolo), which is not modelled.
	// State is Q8 above the 16-bit audio scale.
	// ---------------------------------------------------------------
	logic signed [25:0] d9_t_lp1;
	logic signed [25:0] d9_t_svf_lp;
	logic signed [25:0] d9_t_svf_bp;
	wire  signed [25:0] d9_t_in    = {{2{pc_tone[15]}}, pc_tone, 8'd0};
	wire  signed [25:0] d9_t_d1    = d9_t_in - d9_t_lp1;
	wire  signed [25:0] d9_t_lp1_n = d9_t_lp1 + (d9_t_d1 >>> 2) + (d9_t_d1 >>> 3) - (d9_t_d1 >>> 6);
	wire  signed [25:0] d9_t_lp_n  = d9_t_svf_lp +
		(d9_t_svf_bp >>> 5) + (d9_t_svf_bp >>> 7) + (d9_t_svf_bp >>> 8) +
		(d9_t_svf_bp >>> 10) + (d9_t_svf_bp >>> 11);
	wire  signed [25:0] d9_t_hp    = d9_t_lp1_n - d9_t_lp_n - d9_t_svf_bp;
	wire  signed [25:0] d9_t_bp_n  = d9_t_svf_bp +
		(d9_t_hp >>> 5) + (d9_t_hp >>> 7) + (d9_t_hp >>> 8) +
		(d9_t_hp >>> 10) + (d9_t_hp >>> 11);
	// Output level: the net 0.184 is followed by IC18 / IC28-upper, whose outputs go
	// straight to C57/C61/C107.  Only the BSEL2 VCA (IC28-lower) drives the R219 100k /
	// R220 12k divider, loaded by the F, W and M bus inputs to a tap of 0.0823, and the
	// BSEL2 path here is carried in un-divided units (see mycar_fw_next).  The tunnel
	// path is scaled the same way: 0.184/0.0823 = 2.236 ~ 2 + 1/4 - 1/64 = 2.234.
	wire  signed [25:0] d9_t_out_q8 = (d9_t_lp_n <<< 1) + (d9_t_lp_n >>> 2) - (d9_t_lp_n >>> 6);
	wire  signed [17:0] d9_t_out_s  = d9_t_out_q8 >>> 8;
	wire  signed [15:0] d9_t_out    = (d9_t_out_s >  18'sd32767) ? 16'sd32767 :
									  (d9_t_out_s < -18'sd32768) ? 16'sh8000 : d9_t_out_s[15:0];

	always_ff @(posedge clk) begin
		if (!rst_n) begin
			d9_bsel0_src_fast <= 16'sd0;
			d9_bsel0_src      <= 16'sd0;
			d9_bsel1_src_a <= 16'sd0;
			d9_bsel1_src_b <= 16'sd0;
			d9_bsel1_src_w <= 16'sd0;
			d9_bsel1_w_prev_in <= 16'sd0;
			d9_bsel1_w_hp_q16 <= 40'sd0;
			d9_t_lp1 <= 26'sd0; d9_t_svf_lp <= 26'sd0; d9_t_svf_bp <= 26'sd0;
		end
		else if (sample_ce) begin
			// BSEL0 IC20-A/B net gain precedes the C75 and C93 poles.
			d9_bsel0_src_fast <= d9_src_add(d9_bsel0_src_fast,
				(d9_bsel0_delta_fast >>> 2) +
				(d9_bsel0_delta_fast >>> 3));
			d9_bsel0_src <= d9_src_add(d9_bsel0_src,
				d9_bsel0_alpha_delta_slow);
			// BSEL1 IC23-D/IC24-A: two inverting stages.  C155/C97 belong to the separate
			// IC24-B/C branch (the W-side C155 pole is updated from the same MY CAR CONT source below).
			d9_t_lp1 <= d9_t_lp1_n; d9_t_svf_lp <= d9_t_lp_n; d9_t_svf_bp <= d9_t_bp_n;
			d9_bsel1_src_a <= d9_t_out;
			d9_bsel1_src_b <= d9_t_out;
			d9_bsel1_src_w <= d9_t_out;
			d9_bsel1_w_prev_in <= d9_bsel1_target;
			d9_bsel1_w_hp_q16 <= d9_bsel1_w_hp_next_q16;
		end
	end

	// ---------------------------------------------------------------
	// BCONT0/1/2 gate targets (IC41 74LS139 decoder, one-hot).  BCONT2 is the D9
	// IC35-B/R252/R171/R172/C83/IC24-follower control node.  C83 sits on the
	// R252/R171 junction (node M): selected OC 7417 discharge is R252=1k * C83=1uF =
	// 1 ms; released charge is (R171+R172)=440k * C83 = 440 ms.  The follower sees
	// CONT=(6V+V_M)/2.
	// BCONT0/1 share the 25.5 ms (selected) / 51 ms (unselected) tau of their
	// 51k/51k/1uF network.
	// ---------------------------------------------------------------
	localparam signed [26:0] GAIN_MUTE_Q16 = 27'sd0;
	localparam signed [26:0] GAIN_FULL_Q16 = 27'sd65536;

	localparam signed [26:0] BC2_A_ATTACK_Q16  = 27'sd64185; // exp(-1/(48k*1ms))
	localparam signed [26:0] BC2_B_ATTACK_Q16  = 27'sd1351;  // 65536 - A
	localparam signed [26:0] BC2_A_RELEASE_Q16 = 27'sd65533; // exp(-1/(48k*440ms))
	// No BC2_B_RELEASE_Q16: the release target is GAIN_MUTE_Q16=0, so B*target is
	// always exactly 0 (see OP_BCONT2).

	// MB4391M is the board's dual-MC3340 package.  After IC24-D, CONT is about 3 V when
	// C83 is discharged (selected) and about 6 V when charged (unselected).  The MC3340
	// transfer is strongly nonlinear over that interval; the absolute volts-to-gain
	// scaling is not known, so only the relative MC3340 law is applied.  It is a
	// 49-entry nearest-bin table (no interpolation multiplier, no DSP); gain2_q16
	// remains the C83 envelope.
	function automatic logic signed [26:0] playercar_mc3340_norm(
		input logic signed [26:0] control_q16
	);
		localparam logic signed [26:0] MC3340_NORM_Q16 [0:48] = '{
			27'sd65536, 27'sd62344, 27'sd58334, 27'sd53363, 27'sd47409,
			27'sd39814, 27'sd28519, 27'sd19054, 27'sd12730, 27'sd8505,
			27'sd6052, 27'sd4418, 27'sd3241, 27'sd2391, 27'sd1772,
			27'sd1320, 27'sd988, 27'sd743, 27'sd561, 27'sd425,
			27'sd324, 27'sd248, 27'sd190, 27'sd146, 27'sd113,
			27'sd88, 27'sd68, 27'sd53, 27'sd42, 27'sd33,
			27'sd26, 27'sd21, 27'sd16, 27'sd13, 27'sd10,
			27'sd8, 27'sd7, 27'sd5, 27'sd4, 27'sd4,
			27'sd3, 27'sd2, 27'sd2, 27'sd2, 27'sd2,
			27'sd2, 27'sd2, 27'sd2, 27'sd2
		};
		logic signed [27:0] c;
		logic signed [27:0] inv_c;
		logic signed [35:0] index_product;
		logic [5:0] index;
		begin
			c = (control_q16 < 27'sd0) ? 28'sd0 :
				(control_q16 > GAIN_FULL_Q16) ? $signed({1'b0, GAIN_FULL_Q16}) :
				$signed({control_q16[26], control_q16});
			// gain2=1 -> CONT=3 V -> table index 0; gain2=0 -> CONT=6 V.
			inv_c = $signed({1'b0, GAIN_FULL_Q16}) - c;
			// 48 = 32 + 16.  Use a widened exact shift/add instead of a
			// constant multiply expression so this lookup cannot consume a
			// DSP block merely to form its nearest-bin index.
			index_product = (inv_c <<< 5) + (inv_c <<< 4);
			index = index_product >>> 16;
			if (index > 6'd48)
				index = 6'd48;
			playercar_mc3340_norm = MC3340_NORM_Q16[index];
		end
	endfunction

	localparam signed [26:0] BC01_A_ATTACK_Q16  = 27'sd65482; // exp(-1/(fs*25.5ms))
	localparam signed [26:0] BC01_B_ATTACK_Q16  = 27'sd54;
	localparam signed [26:0] BC01_A_RELEASE_Q16 = 27'sd65509; // exp(-1/(fs*51ms))
	// No BC01_B_RELEASE_Q16: same reasoning as BC2_B_RELEASE_Q24 above.

	wire gate0 = (bsel == 2'd0);
	wire gate1 = (bsel == 2'd1);
	wire gate2 = (bsel == 2'd2);

	logic signed [26:0] gain0_q16, gain1_q16, gain2_q16;
	// The D9 BCONT0/C155 and BCONT1/C97 nodes have the same 3 V selected / 6 V
	// released control span as BCONT2, so all three VCA families use the same relative
	// MC3340 law; the per-family RC states set when each control reaches its endpoint.
	// The finite table stops at its attenuation floor, but an unselected BSEL state is an
	// electrical mute, so that exact endpoint is clamped to avoid a one-count residue in
	// the M bus.
	wire signed [26:0] gain0_mc3340_q16 =
		(gain0_q16 <= 27'sd0) ? 27'sd0 : playercar_mc3340_norm(gain0_q16);
	wire signed [26:0] gain1_mc3340_q16 =
		(gain1_q16 <= 27'sd0) ? 27'sd0 : playercar_mc3340_norm(gain1_q16);   // kept for reference/diagnostics

	// BSEL1 tunnel VCAs: IC18 (F) and IC28-upper (W) each see their own CONT voltage:
	//   CONT_F = V_BCONT1 - d, CONT_W = V_BCONT1 + 1.2 d,  V_BCONT1 = 6 V - 3 V * gain1
	//   (gain1 = the C97 node state), d = the IC38 555 ramp derivative above.
	// GAIN17_LUT_Q16 (1/64-V bins from 3.0 V) turns each into a gain.
	// D9_TUNNEL_KNEE_OFF_IDX shifts the operating point along the table (1/64 V per
	// step); 0 = the MC3340 data-sheet knee, which the MB4391's own (undocumented)
	// knee may differ from.
	localparam int D9_TUNNEL_KNEE_OFF_IDX = 0;
	wire signed [27:0] d9_g1_c      = (gain1_q16 < 27'sd0) ? 28'sd0 :
									  (gain1_q16 > 27'sd65536) ? 28'sd65536 : $signed({gain1_q16[26], gain1_q16});
	wire signed [31:0] d9_v_above3  = ((32'sd65536 - {{4{d9_g1_c[27]}}, d9_g1_c}) <<< 1) + (32'sd65536 - {{4{d9_g1_c[27]}}, d9_g1_c}); // 3*(1-g1), Q16 V
	wire signed [31:0] d9_d_q16     = d9_ramp_d_q24 >>> 8;
	wire signed [31:0] d9_d12_q16   = d9_d_q16 + (d9_d_q16 >>> 2) - (d9_d_q16 >>> 4) + (d9_d_q16 >>> 6);            // 1.203 d
	wire signed [31:0] d9_f_above3  = d9_v_above3 - d9_d_q16;
	wire signed [31:0] d9_w_above3  = d9_v_above3 + d9_d12_q16;
	wire signed [31:0] d9_f_idx_raw = (d9_f_above3 >>> 10) + D9_TUNNEL_KNEE_OFF_IDX;
	wire signed [31:0] d9_w_idx_raw = (d9_w_above3 >>> 10) + D9_TUNNEL_KNEE_OFF_IDX;
	wire [7:0] d9_f_idx = (d9_f_idx_raw < 0) ? 8'd0 : (d9_f_idx_raw > 192) ? 8'd192 : d9_f_idx_raw[7:0];
	wire [7:0] d9_w_idx = (d9_w_idx_raw < 0) ? 8'd0 : (d9_w_idx_raw > 192) ? 8'd192 : d9_w_idx_raw[7:0];
	wire signed [26:0] gain1f_q16 = (gain1_q16 <= 27'sd0) ? 27'sd0 : GAIN17_LUT_Q16[d9_f_idx];
	wire signed [26:0] gain1w_q16 = (gain1_q16 <= 27'sd0) ? 27'sd0 : GAIN17_LUT_Q16[d9_w_idx];

	// DC-block (F/W bus AC coupling, BEHAVIORAL ~20 Hz corner).
	localparam signed [26:0] DCBLOCK_A_Q16 = 27'sd65365;
	logic signed [15:0] dcblock_f_xprev /* verilator public_flat */, dcblock_f_yprev /* verilator public_flat */;
	logic signed [15:0] dcblock_w_xprev, dcblock_w_yprev;

	// SLF = the lower branch of D-8/11 (IC3 and IC5 relaxation cells on the raw ladder,
	// IC17-lower, IC30, R199/R198, C108); see turbo_playercar_slf.sv.
	wire        [7:0]  slf_gain_idx;
	wire signed [26:0] slf_gain_q16 = GAIN17_LUT_Q16[slf_gain_idx];
	wire signed [15:0] slf_dbg_tri, slf_dbg_cont;
	turbo_playercar_slf u_slf (
		.clk(clk), .rst_n(rst_n), .sample_ce(sample_ce),
		.speed_q12(ic3_speed_q12[15:0]), .mycar_off_n(mycar_off_n),
		.gain_idx(slf_gain_idx), .gain_q16(slf_gain_q16),
		.slf_mix(slf_mix), .dbg_ic3_tri(slf_dbg_tri), .dbg_cont_q12(slf_dbg_cont));

	// ---------------------------------------------------------------
	// Shared-multiplier sequencer: ten ops/sample on one shared_mul_lane.  Every
	// operand pair and result is registered; no op's result feeds another op's
	// operand within the same clock.  Same shape as turbo_crash_chan.sv's preamp
	// sequencer.
	// ---------------------------------------------------------------
	typedef enum logic [3:0] {
		OP_IC17, OP_LADDER, OP_BCONT0, OP_BCONT1, OP_BCONT2,
		OP_VCA_Q, OP_VCA_1, OP_VCA_1_W, OP_VCA_2_FW, OP_VCA_2_M,
		OP_DCBLOCK_F, OP_DCBLOCK_W
	} pc_op_t;
	typedef enum logic [1:0] {PC_IDLE, PC_REQ, PC_WAIT, PC_READY} pc_state_t;

	pc_op_t    pc_op;
	pc_state_t pc_seq_state;

	wire signed [55:0] step_target_q16 = $signed({step_target, 16'd0});
	wire signed [55:0] ladder_delta_q16 = step_target_q16 - step_smoothed_q16;

	logic signed [63:0] pc_lane_req_a, pc_lane_req_b;
	logic [6:0] pc_lane_req_a_width, pc_lane_req_b_width;
	logic pc_lane_req_valid, pc_lane_req_ready;
	logic pc_lane_rsp_valid;
	logic signed [127:0] pc_lane_rsp_product;
	logic [7:0] pc_lane_rsp_tag;

	// Operand selection per op: only the issued op's operands matter; unselected
	// branches are dead logic, not extra multiplies.
	always_comb begin
		pc_lane_req_a = 64'sd0;
		pc_lane_req_b = 64'sd0;
		pc_lane_req_a_width = 7'd27;
		pc_lane_req_b_width = 7'd27;
		case (pc_op)
			OP_IC17: begin
				// carrier x IC17 gain (node_ac and ic17_gain_q16 are aligned, see PC_READY commit).
				pc_lane_req_a = {{48{pc_source_shaped[15]}}, pc_source_shaped};
				pc_lane_req_b = {{37{ic17_gain_q16[26]}}, ic17_gain_q16};
				pc_lane_req_a_width = 7'd16;
				pc_lane_req_b_width = 7'd17;
			end
			OP_LADDER: begin
				pc_lane_req_a = {{8{ladder_delta_q16[55]}}, ladder_delta_q16};
				pc_lane_req_b = {{37{LADDER_B_Q16[26]}}, LADDER_B_Q16};
				pc_lane_req_a_width = 7'd56;
				pc_lane_req_b_width = 7'd17;
			end
			OP_BCONT0: begin
				pc_lane_req_a = gate0 ?
					{{37{BC01_A_ATTACK_Q16[26]}}, BC01_A_ATTACK_Q16} :
					{{37{BC01_A_RELEASE_Q16[26]}}, BC01_A_RELEASE_Q16};
				pc_lane_req_b = {{37{gain0_q16[26]}}, gain0_q16};
				pc_lane_req_a_width = 7'd17;
				pc_lane_req_b_width = 7'd17;
			end
			OP_BCONT1: begin
				pc_lane_req_a = gate1 ?
					{{37{BC01_A_ATTACK_Q16[26]}}, BC01_A_ATTACK_Q16} :
					{{37{BC01_A_RELEASE_Q16[26]}}, BC01_A_RELEASE_Q16};
				pc_lane_req_b = {{37{gain1_q16[26]}}, gain1_q16};
				pc_lane_req_a_width = 7'd17;
				pc_lane_req_b_width = 7'd17;
			end
			OP_BCONT2: begin
				pc_lane_req_a = gate2 ?
					{{37{BC2_A_ATTACK_Q16[26]}}, BC2_A_ATTACK_Q16} :
					{{37{BC2_A_RELEASE_Q16[26]}}, BC2_A_RELEASE_Q16};
				pc_lane_req_b = {{37{gain2_q16[26]}}, gain2_q16};
				pc_lane_req_a_width = 7'd17;
				pc_lane_req_b_width = 7'd17;
			end
			OP_VCA_Q: begin
				// IC41 selects one VCA family; an unselected family is muted at the D9 boundary
				// even while its RC control state is still decaying.
				pc_lane_req_a = gate0 ?
					{{48{d9_bsel0_src[15]}}, d9_bsel0_src} : 64'sd0;
				pc_lane_req_b = {{37{gain0_mc3340_q16[26]}}, gain0_mc3340_q16};
				pc_lane_req_a_width = 7'd16;
				pc_lane_req_b_width = 7'd17;
			end
			OP_VCA_1: begin
				pc_lane_req_a = gate1 ?
					{{48{d9_bsel1_src_b[15]}}, d9_bsel1_src_b} : 64'sd0;
				pc_lane_req_b = {{37{gain1f_q16[26]}}, gain1f_q16};
				pc_lane_req_a_width = 7'd16;
				pc_lane_req_b_width = 7'd17;
			end
			OP_VCA_1_W: begin
				pc_lane_req_a = gate1 ?
					{{48{d9_bsel1_src_w[15]}}, d9_bsel1_src_w} : 64'sd0;
				pc_lane_req_b = {{37{gain1w_q16[26]}}, gain1w_q16};
				pc_lane_req_a_width = 7'd16;
				pc_lane_req_b_width = 7'd17;
			end
			OP_VCA_2_FW: begin
				pc_lane_req_a = {{48{pc_tone[15]}}, pc_tone};
				// BSEL2 uses the C83 envelope directly; the relative MC3340 correction applies
				// to the BSEL0/BSEL1 paths above.
				pc_lane_req_b = {{37{gain2_q16[26]}}, gain2_q16};
				pc_lane_req_a_width = 7'd16;
				pc_lane_req_b_width = 7'd17;
			end
			OP_VCA_2_M: begin
				pc_lane_req_a = {{48{pc_tone[15]}}, pc_tone};
				pc_lane_req_b = {{37{gain2_q16[26]}}, gain2_q16};
				pc_lane_req_a_width = 7'd16;
				pc_lane_req_b_width = 7'd17;
			end
			OP_DCBLOCK_F: begin
				pc_lane_req_a = {{48{dcblock_f_yprev[15]}}, dcblock_f_yprev};
				pc_lane_req_b = {{37{DCBLOCK_A_Q16[26]}}, DCBLOCK_A_Q16};
				pc_lane_req_a_width = 7'd16;
				pc_lane_req_b_width = 7'd17;
			end
			OP_DCBLOCK_W: begin
				pc_lane_req_a = {{48{dcblock_w_yprev[15]}}, dcblock_w_yprev};
				pc_lane_req_b = {{37{DCBLOCK_A_Q16[26]}}, DCBLOCK_A_Q16};
				pc_lane_req_a_width = 7'd16;
				pc_lane_req_b_width = 7'd17;
			end
			default: ;
		endcase
	end

	assign pc_lane_req_valid = (pc_seq_state == PC_REQ);

	shared_mul_lane u_playercar_shared_mul_lane (
		.clk(clk), .rst_n(rst_n),
		.req_valid(pc_lane_req_valid), .req_ready(pc_lane_req_ready),
		.req_a(pc_lane_req_a), .req_b(pc_lane_req_b),
		.req_a_width(pc_lane_req_a_width), .req_b_width(pc_lane_req_b_width),
		.req_tag({4'd0, pc_op}),
		.rsp_valid(pc_lane_rsp_valid), .rsp_product(pc_lane_rsp_product),
		.rsp_tag(pc_lane_rsp_tag)
	);

	// Product taps latched from a completed op before the next sample_ce commits
	// them, so the commit stage uses only settled results.
	logic signed [15:0] mycarq_f_next /* verilator public_flat */, mycarq_w_next;
	logic signed [15:0] mycar1_f_next, mycar1_w_next;
	logic signed [15:0] mycar_fw_next /* verilator public_flat */, mycar_m_next;
	logic signed [15:0] dcblock_f_next, dcblock_w_next;
	logic signed [26:0] gain0_next, gain1_next, gain2_next;
	logic signed [55:0] step_smoothed_next;
	logic signed [55:0] sub_step_smoothed_next;
	logic signed [55:0] ic7_step_smoothed_next;
	logic signed [55:0] v_ladder_smoothed_next;

	localparam signed [16:0] FW_LOAD_Q16 = 17'sd21845; // 1/3
	localparam signed [16:0] M_LOAD_Q16  = 17'sd58514;  // 25/28

	function automatic logic signed [15:0] sat16_39(input logic signed [39:0] v);
		begin
			if (v > 40'sd32767) sat16_39 = 16'sd32767;
			else if (v < -40'sd32768) sat16_39 = 16'sh8000;
			else sat16_39 = v[15:0];
		end
	endfunction

	// Arithmetic right shift rounds toward -infinity, which would leave a DC-block
	// limit cycle (e.g. -383 stays -383 under the 0.9974 pole).  The coupling cap must
	// settle to zero, so this signed Q16 pole product truncates toward zero.
	function automatic logic signed [39:0] q16_trunc0(
		input logic signed [127:0] value
	);
		logic signed [127:0] magnitude;
		logic signed [127:0] shifted;
		begin
			if (value < 0) begin
				magnitude = -value;
				shifted = magnitude >>> 16;
				q16_trunc0 = -shifted[39:0];
			end
			else begin
				q16_trunc0 = value >>> 16;
			end
		end
	endfunction

	always_ff @(posedge clk) begin
		if (!rst_n) begin
			pc_seq_state <= PC_IDLE;
			pc_op <= OP_LADDER;
			step_smoothed_q16 <= 56'sd0;
			sub_step_smoothed_q16 <= 56'sd0;
			v_ladder_smoothed_q16 <= 56'sd0;
			gain0_q16 <= GAIN_MUTE_Q16;
			gain1_q16 <= GAIN_MUTE_Q16;
			gain2_q16 <= GAIN_MUTE_Q16;
			step_smoothed_next <= 56'sd0;
			sub_step_smoothed_next <= 56'sd0;
			ic7_step_smoothed_next <= 56'sd0;
			ic7_step_smoothed_q16 <= 56'sd0;
			pc_carrier_gated_next <= 16'sd0;
			v_ladder_smoothed_next <= 56'sd0;
			gain0_next <= GAIN_MUTE_Q16;
			gain1_next <= GAIN_MUTE_Q16;
			gain2_next <= GAIN_MUTE_Q16;
			mycarq_f_next <= 16'sd0;
			mycarq_w_next <= 16'sd0;
			mycar1_f_next <= 16'sd0;
			mycar1_w_next <= 16'sd0;
			mycar_fw_next <= 16'sd0;
			mycar_m_next  <= 16'sd0;
			dcblock_f_next <= 16'sd0;
			dcblock_w_next <= 16'sd0;
			dcblock_f_xprev <= 16'sd0; dcblock_f_yprev <= 16'sd0;
			dcblock_w_xprev <= 16'sd0; dcblock_w_yprev <= 16'sd0;
			player_source_pipe <= 16'sd0;
			player_tone_pipe   <= 16'sd0;
			mycar_f_mix  <= 16'sd0;
			mycar_w_mix  <= 16'sd0;
			mycar_m_mix  <= 16'sd0;
			mycarq_f_mix <= 16'sd0;
			mycarq_w_mix <= 16'sd0;
			mycar1_f_mix <= 16'sd0;
			mycar1_w_mix <= 16'sd0;
			dcblock_f_mix <= 16'sd0;
			dcblock_w_mix <= 16'sd0;
		end else begin
			player_tone_pipe   <= pc_tone;

			case (pc_seq_state)
				PC_IDLE: begin
					if (sample_ce) begin
						pc_op <= OP_IC17;
						pc_seq_state <= PC_REQ;
					end
				end
				PC_REQ: begin
					if (pc_lane_req_ready)
						pc_seq_state <= PC_WAIT;
				end
				PC_WAIT: begin
					if (pc_lane_rsp_valid) begin
						case (pc_op)
							OP_IC17: begin
								pc_carrier_gated_next <=
									sat16_39(($signed(pc_lane_rsp_product[42:0]) >>> 16));
								pc_op <= OP_LADDER;
								pc_seq_state <= PC_REQ;
							end
							OP_LADDER: begin
								step_smoothed_next <= step_smoothed_q16 +
									($signed(pc_lane_rsp_product[72:0]) >>> 16);
								sub_step_smoothed_next <=
									sub_step_smoothed_q16 + sub_step_beta_step_q16;
								ic7_step_smoothed_next <=
									ic7_step_smoothed_q16 + ic7_step_beta_step_q16;
								v_ladder_smoothed_next <=
									v_ladder_smoothed_q16 + v_ladder_beta_step_q16;
								pc_op <= OP_BCONT0;
								pc_seq_state <= PC_REQ;
							end
							OP_BCONT0: begin
								// Release target is GAIN_MUTE_Q16=0, so the B*target term is exactly 0.  Unlike
								// the attack branch (B*FULL>>>16 == B), adding B_RELEASE here would stop the gain
								// short of mute.
								gain0_next <= gate0 ?
									27'(($signed(pc_lane_rsp_product[42:0]) >>> 16) + BC01_B_ATTACK_Q16) :
									27'(($signed(pc_lane_rsp_product[42:0]) >>> 16));
								pc_op <= OP_BCONT1;
								pc_seq_state <= PC_REQ;
							end
							OP_BCONT1: begin
								gain1_next <= gate1 ?
									27'(($signed(pc_lane_rsp_product[42:0]) >>> 16) + BC01_B_ATTACK_Q16) :
									27'(($signed(pc_lane_rsp_product[42:0]) >>> 16));
								pc_op <= OP_BCONT2;
								pc_seq_state <= PC_REQ;
							end
							OP_BCONT2: begin
								gain2_next <= gate2 ?
									27'(($signed(pc_lane_rsp_product[42:0]) >>> 16) + BC2_B_ATTACK_Q16) :
									27'(($signed(pc_lane_rsp_product[42:0]) >>> 16));
								pc_op <= OP_VCA_Q;
								pc_seq_state <= PC_REQ;
							end
							OP_VCA_Q: begin
								mycarq_f_next <= sat16_39(($signed(pc_lane_rsp_product[42:0]) >>> 16));
								mycarq_w_next <= sat16_39(($signed(pc_lane_rsp_product[42:0]) >>> 16));
								pc_op <= OP_VCA_1;
								pc_seq_state <= PC_REQ;
							end
			OP_VCA_1: begin
				mycar1_f_next <= sat16_39(($signed(pc_lane_rsp_product[42:0]) >>> 16));
				pc_op <= OP_VCA_1_W;
				pc_seq_state <= PC_REQ;
			end
			OP_VCA_1_W: begin
				mycar1_w_next <= sat16_39(($signed(pc_lane_rsp_product[42:0]) >>> 16));
				pc_op <= OP_VCA_2_FW;
				pc_seq_state <= PC_REQ;
			end
							OP_VCA_2_FW: begin
								// The loaded-feed 1/3 vs 25/28 split is applied after the multiply by a fixed
								// shift in the commit stage (mycar_fw_next/mycar_m_next), so this op stays a
								// single non-chained multiply of tone*gain2.
								mycar_fw_next <= sat16_39(($signed(pc_lane_rsp_product[42:0]) >>> 16));
								pc_op <= OP_VCA_2_M;
								pc_seq_state <= PC_REQ;
							end
							OP_VCA_2_M: begin
								mycar_m_next <= sat16_39(($signed(pc_lane_rsp_product[42:0]) >>> 16));
								pc_op <= OP_DCBLOCK_F;
								pc_seq_state <= PC_REQ;
							end
							OP_DCBLOCK_F: begin
								dcblock_f_next <= sat16_39(
									(mycarq_f_next + mycar1_f_next + mycar_fw_next)
									- dcblock_f_xprev
									+ q16_trunc0(pc_lane_rsp_product));
								pc_op <= OP_DCBLOCK_W;
								pc_seq_state <= PC_REQ;
							end
							OP_DCBLOCK_W: begin
								dcblock_w_next <= sat16_39(
									(mycarq_w_next + mycar1_w_next + mycar_fw_next)
									- dcblock_w_xprev
									+ q16_trunc0(pc_lane_rsp_product));
								pc_seq_state <= PC_READY;
							end
							default: pc_seq_state <= PC_READY;
						endcase
					end
				end
				PC_READY: begin
					// Commit all results together one sample_ce after the sequence started
					// (gain2_q16 is still the old value that OP_BCONT2 read).
					step_smoothed_q16 <= step_smoothed_next;
					sub_step_smoothed_q16 <= sub_step_smoothed_next;
					ic7_step_smoothed_q16 <= ic7_step_smoothed_next;
					// The IC17-gated carrier becomes the D9 source for the next sample.
					player_source_pipe <= pc_carrier_gated_next;
					v_ladder_smoothed_q16 <= v_ladder_smoothed_next;
					gain0_q16 <= gain0_next;
					gain1_q16 <= gain1_next;
					gain2_q16 <= gain2_next;
					// IC41's /MYCAR OFF is a decoder mute, not a slow VCA release.  A completed
					// shared-multiply sequence could otherwise commit one stale result after BSEL
					// changes to 3 and leave a coupling-cap tail, so the whole D9 audio boundary is
					// clamped and both coupling-cap states are cleared here.
					if (bsel == 2'd3) begin
						mycarq_f_mix <= 16'sd0;
						mycarq_w_mix <= 16'sd0;
						mycar1_f_mix <= 16'sd0;
						mycar1_w_mix <= 16'sd0;
						mycar_f_mix  <= 16'sd0;
						mycar_w_mix  <= 16'sd0;
						mycar_m_mix  <= 16'sd0;
						dcblock_f_xprev <= 16'sd0;
						dcblock_f_yprev <= 16'sd0;
						dcblock_w_xprev <= 16'sd0;
						dcblock_w_yprev <= 16'sd0;
						dcblock_f_mix <= 16'sd0;
						dcblock_w_mix <= 16'sd0;
					end else begin
						mycarq_f_mix <= mycarq_f_next;
						mycarq_w_mix <= mycarq_w_next;
						mycar1_f_mix <= mycar1_f_next;
						mycar1_w_mix <= mycar1_w_next;
						// A concatenation {...} is unsigned in Verilog regardless of its parts, so each
						// sign-extended operand is wrapped in $signed() to keep the multiply signed.
						mycar_f_mix  <= sat16_39($signed({{24{mycar_fw_next[15]}}, mycar_fw_next}) *
												  $signed({48'd0, FW_LOAD_Q16}) >>> 16);
						mycar_w_mix  <= sat16_39($signed({{24{mycar_fw_next[15]}}, mycar_fw_next}) *
												  $signed({48'd0, FW_LOAD_Q16}) >>> 16);
						mycar_m_mix  <= sat16_39($signed({{24{mycar_m_next[15]}}, mycar_m_next}) *
												  $signed({48'd0, M_LOAD_Q16}) >>> 16);
						dcblock_f_xprev <= (mycarq_f_next + mycar1_f_next + mycar_fw_next);
						dcblock_f_yprev <= dcblock_f_next;
						dcblock_w_xprev <= (mycarq_w_next + mycar1_w_next + mycar_fw_next);
						dcblock_w_yprev <= dcblock_w_next;
						// Combined AC-coupled F/W: the final F/W mixer inputs.
						dcblock_f_mix <= dcblock_f_next;
						dcblock_w_mix <= dcblock_w_next;
					end
					pc_seq_state <= PC_IDLE;
				end
				default: pc_seq_state <= PC_IDLE;
			endcase
		end
	end

`ifdef VERILATOR_SIM
	// The commit stage uses a raw `*` on FW_LOAD_Q16/M_LOAD_Q16: single-constant
	// operands that Quartus folds into shift/add, so no extra lane ops are needed.
	always_ff @(posedge clk) begin
		if (rst_n && sample_ce)
			assert (pc_seq_state == PC_IDLE || pc_seq_state == PC_READY);
	end
`endif

endmodule
